# Should run with the "dev" profile

turms:
  service:
    admin-api:
      address:
        advertise-strategy: public_address
    message:
      allow-send-messages-to-oneself: true
      allow-send-messages-to-stranger: true