global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - 'node-exporter:9100'

  - job_name: 'cAdvisor'
    static_configs:
      - targets:
          - 'cAdvisor:8080'

  - job_name: 'mongo-exporter'
    static_configs:
      - targets:
          - 'mongo-exporter:9216'

  - job_name: 'redis-exporter'
    static_configs:
      - targets:
          - 'redis-exporter:9121'

  - job_name: 'turms-gateway'
    metrics_path: '/metrics/prometheus'
    metric_relabel_configs:
      - source_labels:
          - __name__
        replacement: 'turms_gateway_${1}'
        target_label: __name__
    static_configs:
      - targets:
          - 'turms-gateway:9510'

  - job_name: 'turms-service'
    metrics_path: '/metrics/prometheus'
    metric_relabel_configs:
      - source_labels:
          - __name__
        replacement: 'turms_service_${1}'
        target_label: __name__
    static_configs:
      - targets:
          - 'turms-service:8510'