name: Publish turms-admin

on: [ push, pull_request ]

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build turms-admin image
        # FIXME: We use the root context currently because turms-admin requires turms-client-js,
        # which doesn't have a publish workflow for now.
        run: DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64,linux/arm64 --rm=false -t "ghcr.io/turms-im/turms-admin:latest" -f turms-admin/Dockerfile .

      - name: Docker login
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        run: docker login ghcr.io -u $GITHUB_ACTOR -p $GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish turms-admin (Use cache)
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        run: DOCKER_BUILDKIT=1 docker buildx build --platform linux/amd64,linux/arm64 --tag "ghcr.io/turms-im/turms-admin:latest" --push -f turms-admin/Dockerfile .