name: Test turms-admin

on: [ push, pull_request ]

jobs:
  ui-tests:
    runs-on: ubuntu-20.04
    container: cypress/browsers:node16.14.0-chrome99-ff97
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: turms-admin
          build: npm run build
          start: npm run serve
          wait-on: 'http://localhost:6510'