name: turms_client_dart
version: 1.0.0
homepage: https://github.com/turms-im/turms

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  fixnum: ^1.0.1
  http: ^0.13.5
  protobuf: ^2.1.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.21.6
